version: '3.8'

services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: apache7.2
    ports:
      - 8080:80
    volumes: 
      - .:/var/www/html
    depends_on:
      - dbService

  dbService:
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysqlDB
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
  
  phpmyadmin:
    depends_on:
      - dbService
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: phpmyadmin
    ports:
      - 18080:80
    environment:
      PMA_HOST: dbService
      MYSQL_ROOT_PASSWORD: password